# Autogenerated wrapper script for slope_jll for x86_64-apple-darwin-julia_version+1.7.0
export libslopejll

using CompilerSupportLibraries_jll
using LLVMOpenMP_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("slope")
JLLWrappers.@declare_library_product(libslopejll, "@rpath/libslopejll.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, LLVMOpenMP_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libslopejll,
        "lib/libslopejll.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
