# Autogenerated wrapper script for slope_jll for x86_64-w64-mingw32-cxx11-julia_version+1.13.0
export libslopejll

using CompilerSupportLibraries_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("slope")
JLLWrappers.@declare_library_product(libslopejll, "libslopejll.dll")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        libslopejll,
        "bin\\libslopejll.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
